cache:
  directories:
    - $HOME/.composer/cache

language: php

env:
  global:
    - COVERAGE=0

matrix:
  include:
    - php: 7.3
      env: COVERAGE=1 LARAVEL='8.* 'TESTBENCH='5.*' COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
      env: COVERAGE=1 LARAVEL='8.* 'TESTBENCH='5.*' COMPOSER_FLAGS=""
    - php: 7.4
      env: COVERAGE=1 LARAVEL='8.* 'TESTBENCH='5.*' COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: COVERAGE=1 LARAVEL='8.* 'TESTBENCH='5.*' COMPOSER_FLAGS=""
  fast_finish: true

before_script:
    - composer config discard-changes true
    - if [[ $COVERAGE = '1' ]]; then ./bin/codeclimate setup; fi

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update ${COMPOSER_FLAGS}

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

after_success:
  - if [[ $COVERAGE = 1 ]]; then ./bin/codeclimate report $TRAVIS_TEST_RESULT; fi
