name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 * * *
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.3'
        laravel:
          - '9.*'
          - '8.*'
          - '7.*'
        deps:
          - lowest
          - latest
        exclude:
          - {php: '8.1', deps: 'lowest'}
          - {php: '8.0', deps: 'lowest'}
          - {php: '8.1', laravel: '7.*'}
          - {php: '7.4', laravel: '9.*'}
          - {php: '7.3', laravel: '9.*'}
    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.deps }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: >-
            dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php
            }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          coverage: none

      - name: Install Laravel ${{ matrix.laravel }}
        run: composer require "laravel/framework:${{ matrix.laravel }}" --with-all-dependencies --no-interaction

      - name: Install dependencies (lowest)
        if: ${{ matrix.deps == 'lowest' }}
        run: composer update --prefer-lowest --prefer-dist --no-interaction --no-suggest

      - name: Install dependencies (latest)
        if: ${{ matrix.deps != 'lowest' }}
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
